version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  run_test:
    jobs:
      - test
