version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Run tests
          command: npm test
workflows:
  run_test:
    jobs:
      - test
